# Generated by Django 5.0 on 2023-12-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("H", "high"), ("M", "Medium"), ("L", "Low")], max_length=1
            ),
        ),
    ]
