# Generated by Django 5.0 on 2023-12-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_remove_task_photo_alter_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="task_photos", to="tasks.image"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("H", "High"), ("M", "Medium"), ("L", "Low")], max_length=1
            ),
        ),
    ]
