# Generated by Django 5.0 on 2023-12-15 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_task_photos_alter_task_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="photos",
        ),
    ]
